apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/mqtt'
    targetRevision: HEAD
    path: 'path/to/mqtt/manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mqtt-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
